# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jin-Blog
avatar: /static/duola.jpg
favicon: /static/blog.ico
# subtitle: '记录生活与思考'
logo:
  subtitle: '我们永远不知道生活下一刻会发生什么 | 所以要时刻准备着' # '文字1 | 文字2' (鼠标放上去会切换到文字2)
description: '专注于个人成长与计算机技术的博客'
keywords: 后端, C, Cplusplus, SQL, Linux, 博客, 技术
author: Vestjin
language: 
  - zh-CN
  - en 
timezone: 'Asia/Shanghai'

# 文章类型 
article:
  type: tech # tech/story
  share: [wechat, weibo, email, link]


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://code-mist.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search:
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    skip_search: [] # 指定 path 中的内容不被搜索。
    codeblock: true # 是否搜索代码块（需要content: true)

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
# 代码块高亮 hilight code sinapt
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  line_threshold: 0 
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0 
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
#   type: git
#   repo: https://github.com/code-mist/code-mist.github.io  # 仓库地址
#   branch: publish   # 发布分支，GitHub Pages 通常为 gh-pages 或 main（取决于你的设置）
#   message: # 可选，提交信息
